"""
Launch a fleet (N devices plus the gateway) in one Renode instance from a
script generated by tools/fleetgen.py, and hand out a tools.fleet.Fleet
client bound to it.

The harness holds the monitor and every device UART; the Fleet client owns
the gateway socket (Renode's socket terminal serves one client at a time).
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

from renode_harness import REPO_ROOT, LineReader, Monitor, free_tcp_port, wait_for_port

sys.path.insert(0, str(REPO_ROOT / "tools"))
import fleet as fleet_mod  # noqa: E402
import fleetgen  # noqa: E402


class FleetLab:
    def __init__(self, artifacts, images, log_dir: Path, renode: str | None = None):
        self.artifacts = artifacts
        self.images = list(images)
        self.nodes = list(range(len(self.images)))
        self.log_dir = log_dir
        self.renode = renode or os.environ.get("RENODE", "renode")
        self.monitor_port = free_tcp_port()
        self.gw_port = free_tcp_port()
        self.uart_ports = [free_tcp_port() for _ in self.nodes]
        self.proc = None
        self.monitor = None
        self.dut_uarts: list[LineReader] = []
        self.fleet: fleet_mod.Fleet | None = None
        self.log_dir.mkdir(parents=True, exist_ok=True)

    def start(self) -> "FleetLab":
        flash_paths = [img.write(self.log_dir / f"node{n}.bin") for n, img in enumerate(self.images)]
        script = self.log_dir / "fleet.resc"
        script.write_text(
            f"logFile @{(self.log_dir / 'renode.log').as_posix()}\n" +
            fleetgen.generate(len(self.nodes), self.artifacts.boot_elf, self.artifacts.gateway_elf,
                              REPO_ROOT / "renode/stm32f4_ota.repl", flash_paths, self.uart_ports, self.gw_port),
            encoding="utf-8", newline="\n")
        exe = shutil.which(self.renode) or self.renode
        self._stdout = open(self.log_dir / "renode-stdout.log", "wb")
        self.proc = subprocess.Popen([exe, "--disable-gui", "-P", str(self.monitor_port), script.as_posix()],
                                     cwd=REPO_ROOT, stdin=subprocess.DEVNULL, stdout=self._stdout,
                                     stderr=subprocess.STDOUT)
        try:
            self.monitor = Monitor(wait_for_port(self.monitor_port, 120.0))
            self.monitor.wait_ready(10.0)
            for n in self.nodes:
                self.dut_uarts.append(LineReader(wait_for_port(self.uart_ports[n], 120.0), f"dut{n}-uart", self.check_alive))
            deadline = time.monotonic() + 120.0
            while time.monotonic() < deadline:
                self.monitor.command('mach set "gateway"', timeout=10.0)
                if self.monitor.last_prompt == "(gateway) ":
                    break
                time.sleep(0.5)
            else:
                raise TimeoutError("fleet script did not finish creating machines")
            self.monitor.command('mach set "dut0"')
            # The Fleet client connects to the gateway socket before start so
            # no reply is ever missed; it reads virtual time via its own
            # monitor connection.
            self.fleet = fleet_mod.Fleet("127.0.0.1", self.gw_port, self.nodes, say=lambda m: None,
                                         clock=self.virtual_time_s, clock_label="Renode virtual seconds")
            self.monitor.command("start")
        except Exception:
            self.stop()
            raise
        return self

    def check_alive(self) -> None:
        if self.proc is not None and self.proc.poll() is not None:
            raise RuntimeError(f"Renode exited with code {self.proc.returncode}")

    def wait_all_ready(self, timeout: float = 120.0) -> None:
        for n in self.nodes:
            self.dut_uarts[n].expect(r"^(boot: ok|waiting for update)$", timeout)

    def virtual_time_s(self) -> float:
        out = self.monitor.command("machine ElapsedVirtualTime")
        import re
        m = re.search(r"Elapsed Virtual Time: (\d+):(\d+):(\d+)\.(\d+)", out)
        h, mi, s, frac = m.groups()
        return int(h) * 3600 + int(mi) * 60 + int(s) + int(frac) / 10 ** len(frac)

    def stop(self) -> None:
        if self.fleet:
            self.fleet.close()
            self.fleet = None
        for n, r in enumerate(self.dut_uarts):
            r.close()
            (self.log_dir / f"dut{n}-uart.txt").write_text("\n".join(l.text for l in r.history) + "\n")
        if self.monitor:
            try:
                self.monitor.sock.sendall(b"quit\n")
            except OSError:
                pass
            self.monitor.close()
        if self.proc:
            try:
                self.proc.wait(timeout=15)
            except subprocess.TimeoutExpired:
                self.proc.kill()
                self.proc.wait()
        if getattr(self, "_stdout", None):
            self._stdout.close()
