"""
Generate the Renode script for a fleet: N devices under test plus one CAN
gateway on a shared bus. Each device gets its own machine, its own flash
image file, its own UART socket, and its node id written into the STM32
unique-ID area so the firmware derives its CAN identifiers from it.

    python tools/fleetgen.py --nodes 5 --out build/fleet/fleet.resc
    renode build/fleet/fleet.resc

The generator is the only place fleet scripts come from; the single-device
lab script renode/ota_lab.resc stays hand-written.
"""
from __future__ import annotations

import argparse
from pathlib import Path

UID_ADDR = 0x1FFF7A10

HEADER = """:name: OTA lab fleet
:description: {nodes} devices under test plus a CAN-to-UART gateway on one CAN bus. Generated by tools/fleetgen.py.

emulation CreateCANHub "canbus"
emulation CreateServerSocketTerminal {gw_port} "gw_term" false
"""

DEVICE = """
# ---- node {n}
emulation CreateServerSocketTerminal {uart_port} "dut{n}_term" false
mach create "dut{n}"
machine LoadPlatformDescription @{repl}
sysbus LoadELF @{boot_elf}
sysbus LoadBinary @{flash} 0x08000000
sysbus WriteDoubleWord {uid_addr:#x} {n}
connector Connect sysbus.usart2 dut{n}_term
connector Connect sysbus.can1 canbus
macro reset
\"\"\"
    sysbus LoadELF @{boot_elf}
\"\"\"
logLevel 3 sysbus.flash_controller
"""

GATEWAY = """
# ---- gateway
mach create "gateway"
machine LoadPlatformDescription @{repl}
sysbus LoadELF @{gw_elf}
connector Connect sysbus.usart2 gw_term
connector Connect sysbus.can1 canbus

mach set "dut0"
# Start with: start
"""


def generate(nodes: int, boot_elf, gw_elf, repl, flash_paths, uart_ports, gw_port) -> str:
    if not 1 <= nodes <= 15:
        raise ValueError("nodes must be 1..15")
    if len(flash_paths) != nodes or len(uart_ports) != nodes:
        raise ValueError("one flash image and one UART port per node")
    out = [HEADER.format(nodes=nodes, gw_port=gw_port)]
    for n in range(nodes):
        out.append(DEVICE.format(
            n=n, uart_port=uart_ports[n], repl=Path(repl).as_posix(),
            boot_elf=Path(boot_elf).as_posix(), flash=Path(flash_paths[n]).as_posix(),
            uid_addr=UID_ADDR,
        ))
    out.append(GATEWAY.format(repl=Path(repl).as_posix(), gw_elf=Path(gw_elf).as_posix()))
    return "".join(out)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--nodes", type=int, default=5)
    ap.add_argument("--boot-elf", default=root / "build/firmware/boot/boot.elf")
    ap.add_argument("--gw-elf", default=root / "build/firmware/can_gateway/can_gateway.elf")
    ap.add_argument("--repl", default=root / "renode/stm32f4_ota.repl")
    ap.add_argument("--flash", default=root / "build/flash/default.bin",
                    help="flash image used for every node unless --flash-dir is given")
    ap.add_argument("--flash-dir", help="directory holding node0.bin .. nodeN.bin")
    ap.add_argument("--uart-base", type=int, default=3460, help="node n listens on uart-base + n")
    ap.add_argument("--gw-port", type=int, default=3457)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    if args.flash_dir:
        flash_paths = [Path(args.flash_dir) / f"node{n}.bin" for n in range(args.nodes)]
    else:
        flash_paths = [Path(args.flash)] * args.nodes
    text = generate(args.nodes, args.boot_elf, args.gw_elf, args.repl, flash_paths,
                    [args.uart_base + n for n in range(args.nodes)], args.gw_port)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {out} for {args.nodes} nodes; gateway on {args.gw_port}, "
          f"UARTs on {args.uart_base}..{args.uart_base + args.nodes - 1}")


if __name__ == "__main__":
    main()
