#!/usr/bin/env python3
"""
Generate an Ed25519 signing key pair for the OTA lab.

Writes:
  <dir>/<name>.key   32 byte private seed, hex
  <dir>/<name>.pub   32 byte public key, hex
  <c-out>            C source with the public key for the bootloader

Usage:
  python tools/keygen.py --dir keys --name dev_ed25519 --c-out firmware/boot/public_key.c
"""
import argparse
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dir", default="keys")
    ap.add_argument("--name", default="dev_ed25519")
    ap.add_argument("--c-out", default="firmware/boot/public_key.c")
    ap.add_argument("--force", action="store_true", help="overwrite an existing key")
    args = ap.parse_args()

    key_dir = Path(args.dir)
    key_dir.mkdir(parents=True, exist_ok=True)
    priv_path = key_dir / f"{args.name}.key"
    pub_path = key_dir / f"{args.name}.pub"
    if priv_path.exists() and not args.force:
        raise SystemExit(f"{priv_path} exists; use --force to overwrite")

    key = Ed25519PrivateKey.generate()
    seed = key.private_bytes_raw()
    pub = key.public_key().public_bytes_raw()

    priv_path.write_text(seed.hex() + "\n", encoding="utf-8")
    pub_path.write_text(pub.hex() + "\n", encoding="utf-8")

    words = ", ".join(f"0x{b:02X}" for b in pub)
    c_src = (
        "/* Generated by tools/keygen.py. Public half of keys/%s.key.\n"
        " * The bootloader accepts only images signed with the matching private key. */\n"
        "#include <stdint.h>\n\n"
        "const uint8_t boot_public_key[32] = {\n    %s\n};\n"
    ) % (args.name, "\n    ".join(", ".join(f"0x{b:02X}" for b in pub[i:i + 8]) + "," for i in range(0, 32, 8)))
    Path(args.c_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.c_out).write_text(c_src, encoding="utf-8")
    print(f"wrote {priv_path}, {pub_path}, {args.c_out}")
    print(f"public key: {pub.hex()}")
    del words


if __name__ == "__main__":
    main()
